version: '3'
services:
  node:
    container_name: nodejs
    restart: always
    build: .
    ports:
      - '3000:3000'
    external_links:
      - mysql
  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: 'node_schema'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
